<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>RepositorioBinario</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <NoWarn>SYSLIB0011</NoWarn>
  </PropertyGroup>

  <Target Name="CopyData" AfterTargets="Build">
    <ItemGroup>
      <DataFiles Include="Data\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(DataFiles)" DestinationFolder="$(OutputPath)Data\%(RecursiveDir)" />
  </Target>

</Project>